# This workflow will build a container and deploy it to an Azure Functions App on Linux when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure Functions app.
# For instructions see https://learn.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image?tabs=in-process%2Cbash%2Cazure-cli&pivots=programming-language-csharp
#
# To configure this workflow:
# 1. Set up the following secrets in your repository:
#   - AZURE_RBAC_CREDENTIALS
#   - REGISTRY_USERNAME
#   - REGISTRY_PASSWORD
# 2. Change env variables for your configuration.
#
# For more information on:
#   - GitHub Actions for Azure: https://github.com/Azure/Actions
#   - Azure Functions Container Action: https://github.com/Azure/functions-container-action
#   - Azure Service Principal for RBAC: https://github.com/Azure/functions-action#using-azure-service-principal-for-rbac-as-deployment-credential
#
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples/tree/master/FunctionApp

name: Deploy container to Azure Functions App

on:
  push:
    branches: ["main"]
    paths:
      - "Node/API2/**"
  workflow_dispatch:

permissions:
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: 519-function-app   # set this to your function app name on Azure
  LOGIN_SERVER: 519assignment2              # set this to login server for your private container registry (e.g. 'contoso.azurecr.io', 'index.docker.io' )
  REGISTRY: 519assignment2                 # set this to proper value for REGISTRY
  NAMESPACE: 519-function-app              # set this to proper value for NAMESPACE
  IMAGE: hello-world                       # set this to proper value for IMAGE
  TAG: latest                           # set this to proper value for TAG

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.CONTAINER_SECRET }}

    - name: 'Build and deploy Container App'
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}/Node/API2
        containerAppName: assignment2
        resourceGroup: 519-web-app_group
        acrName: 519assignment2
        environmentVariables: mystorageconnectionappsetting=secretref:mystorageconnectionappsetting
        
      
    

        
      

    - name: Azure logout
      run: |
        az logout
