name: Deploy Node.js to Azure Web App

on:
  push

env:
  AZURE_WEBAPP_NAME: 519-web-app
  AZURE_WEBAPP_PACKAGE_PATH: 'Node/WEB'  # Ensure this path is correct
  FRONTEND_PACKAGE_PATH: 'Node/WEB/frontend'  # Ensure this path is correct
  NODE_VERSION: '20.x'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install for backend
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: npm install

      - name: npm install for frontend
        working-directory: ${{ env.FRONTEND_PACKAGE_PATH }}
        run: |
          npm install
          npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .  # Update this path to the location of your build artifacts

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Download artifact from build job'
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App using Publish Profile'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./node-app  # Ensure this points to the downloaded artifact
