name: Deploy Node.js to Azure Web App

on:
  [push]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: 519-web-app    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'Node/WEB'      # set this to the path to your web app project, defaults to the repository root
  FRONTEND_PACKAGE_PATH: 'Node/WEB/frontend'
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './Node/WEB/package.json'

      - name: npm install, build, and test
        working-directory: '${{ env.WEBAPP_PACKAGE_PATH }}'
        run: |
          npm install

      - name: npm install react frontend
        working-directory: './${{ env.FRONTEND_PACKAGE_PATH }}'
        run: npm install
             npm run build
             rm -r public
             rm -r node_modules
             rm -r src

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

  deploy:
    permissions: 
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  
  # For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
  # For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples